### ISSUE TITLE
[FEAT] 병원 인증 API

### ISSUE THREAD

**Issue by eminentecero** [eyear22/eyear_backend#1]
## Issue

병원 인증하기 API

## Todo

- [ ] 보건의료 API 들고오기
- [x] 구동 되는지 확인해보기
- [ ] 병원인증 API 생성
