### ISSUE TITLE
keyword 추출

### ISSUE THREAD

**Issue by Chaerim1001** [eyear22/eyear_backend#12]
## Issue

문장의 핵심 키워드 추출

## Todo

- [x] 핵심 키워드 추출 파이썬 코드 JS로 연결
- [x] 키워드 DB 생성
- [x] 자막 불러와서 키워드 추출 후에 DB 저장

**Comment by Chaerim1001** [comment]
done
