### ISSUE TITLE
[FEAT] Cloud API 연동

### ISSUE THREAD

**Issue by eminentecero** [eyear22/eyear_backend#16]
## Issue

Cloud API와 편지 API 연결

## Todo

- [x] cloud API 모듈화
- [x] 편지 보내기 API와 연결
- [x] 키워드 로직과 합치기
